### PR TITLE
chore: update to go 1.18

### PR DESCRIPTION
**Pull request by RafilxTenfen**
- Moved from go 1.17 to 1.18

### CODE REVIEW

**Review by facundomedica — APPROVED** [review]

**Review by facundomedica — CHANGES_REQUESTED** [review]
We still need to change the version in the workflows

**Comment by RafilxTenfen** [comment]
> We still need to change the version in the workflows

Good catch

**Comment by RafilxTenfen** [comment]
> We still need to change the version in the workflows

Done ^^
The only workflow that is not at go 1.18 is the linter that needs the 1.19

**Review by facundomedica — APPROVED** [review]
lfg!

**Pull request merged**
